// AUTO-GENERATED by scripts/prepare-gallery-assets.mjs — do not edit by hand.
const pad = (i: number) => String(i).padStart(3, '0')

export const naneghatFrames = {
  count: 72,
  lg: (i: number) => `/gallery/naneghat/frames/lg/f-${pad(i)}.webp`,
  sm: (i: number) => `/gallery/naneghat/frames/sm/f-${pad(i)}.webp`,
  lgSize: { width: 1080, height: 1920 },
  smSize: { width: 720, height: 1280 },
} as const

export type GalleryFrames = typeof naneghatFrames
